import { Navigate, Link, useParams } from 'react-router-dom';
import { ExternalLink } from 'lucide-react';
import { SEO } from '@/components/ui/SEO';
import { SectionHeader } from '@/components/ui/SectionHeader';
import { LinkButton } from '@/components/ui/Button';
import { getProject, projects } from '@/data/projects';
import { breadcrumbSchema } from '@/lib/seo';

function CaseBlock({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-[2rem] border border-soft bg-card p-7"><h2 className="font-display text-2xl font-black">{title}</h2><div className="mt-4 text-muted">{children}</div></div>; }

export function CaseStudy() {
  const { slug } = useParams();
  const project = slug ? getProject(slug) : undefined;
  if (!project) return <Navigate to="/404" replace />;
  const related = projects.filter((p) => p.slug !== project.slug && p.category === project.category).slice(0, 3);
  const schema = breadcrumbSchema([{ name: 'Home', url: '/' }, { name: 'Work', url: '/work' }, { name: project.title, url: `/work/${project.slug}` }]);
  return <><SEO title={`${project.title} Case Study — ROVIK`} description={project.summary} path={`/work/${project.slug}`} schema={schema} /><section className="section-pad"><div className="container"><p className="kicker">Case Study · {project.category}</p><h1 className="h1 mt-4 max-w-5xl">{project.title}</h1><p className="mt-6 max-w-3xl text-xl leading-9 text-muted">{project.summary}</p><div className="mt-8 flex flex-wrap gap-3"><a href={project.url} target="_blank" rel="noreferrer" className="focus-ring inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-bold text-white dark:bg-white dark:text-ink">Visit project <ExternalLink className="h-4 w-4"/></a><LinkButton to="/project-builder" variant="secondary">Build similar project</LinkButton></div><div className={`mt-12 h-[420px] rounded-[2.5rem] bg-gradient-to-br ${project.palette} border border-soft`} /></div></section><section className="section-pad bg-card"><div className="container grid gap-5 md:grid-cols-2"><CaseBlock title="Problem"><p>{project.problem}</p></CaseBlock><CaseBlock title="Objective"><p>{project.objective}</p></CaseBlock><CaseBlock title="Solution"><p>{project.solution}</p></CaseBlock><CaseBlock title="Tech Stack"><div className="flex flex-wrap gap-2">{project.stack.map((item) => <span className="rounded-full border border-soft px-3 py-1 text-xs font-bold" key={item}>{item}</span>)}</div></CaseBlock><CaseBlock title="Product Features"><ul className="space-y-2">{project.features.map((item) => <li key={item}>✓ {item}</li>)}</ul></CaseBlock><CaseBlock title="Design"><ul className="space-y-2">{project.design.map((item) => <li key={item}>✓ {item}</li>)}</ul></CaseBlock><CaseBlock title="Engineering"><ul className="space-y-2">{project.engineering.map((item) => <li key={item}>✓ {item}</li>)}</ul></CaseBlock><CaseBlock title="Challenges"><ul className="space-y-2">{project.challenges.map((item) => <li key={item}>✓ {item}</li>)}</ul></CaseBlock><CaseBlock title="Results"><ul className="space-y-2">{project.results.map((item) => <li key={item}>✓ {item}</li>)}</ul><p className="mt-4 text-sm">No invented revenue, fake testimonials or unverified metrics are used.</p></CaseBlock><CaseBlock title="Gallery"><div className="grid grid-cols-2 gap-3">{[0,1,2,3].map((i) => <div key={i} className={`h-28 rounded-2xl bg-gradient-to-br ${project.palette}`} />)}</div></CaseBlock></div></section><section className="section-pad"><div className="container"><SectionHeader eyebrow="Related" title="Related projects"/><div className="grid gap-4 md:grid-cols-3">{related.length ? related.map((item) => <Link key={item.slug} to={`/work/${item.slug}`} className="rounded-3xl border border-soft bg-card p-6"><h3 className="font-display text-2xl font-black">{item.title}</h3><p className="mt-3 text-sm text-muted">{item.summary}</p></Link>) : <Link to="/work" className="rounded-3xl border border-soft bg-card p-6">View all projects</Link>}</div></div></section></>;
}
