import { Navigate, Link, useParams } from 'react-router-dom';
import * as Icons from 'lucide-react';
import { SEO } from '@/components/ui/SEO';
import { SectionHeader } from '@/components/ui/SectionHeader';
import { LinkButton } from '@/components/ui/Button';
import { getService } from '@/data/services';
import { projects } from '@/data/projects';
import { breadcrumbSchema } from '@/lib/seo';

export function ServiceDetail() {
  const { slug } = useParams();
  const service = slug ? getService(slug) : undefined;
  if (!service) return <Navigate to="/404" replace />;
  const Icon = (Icons as any)[service.icon] || Icons.Sparkles;
  const related = projects.filter((project) => service.relatedProjectSlugs.includes(project.slug));
  const schema = [breadcrumbSchema([{ name: 'Home', url: '/' }, { name: 'Services', url: '/services' }, { name: service.title, url: `/services/${service.slug}` }]), { '@context': 'https://schema.org', '@type': 'Service', name: service.title, provider: { '@type': 'Organization', name: 'ROVIK' }, description: service.summary }];
  return <><SEO title={`${service.title} by ROVIK`} description={service.summary} path={`/services/${service.slug}`} schema={schema} /><section className="section-pad"><div className="container"><div className="grid gap-10 lg:grid-cols-[1fr_.72fr]"><div><div className="mb-6 grid h-16 w-16 place-items-center rounded-3xl bg-gradient-to-br from-electric to-violet text-white"><Icon className="h-8 w-8"/></div><p className="kicker">{service.eyebrow}</p><h1 className="h1 mt-4">{service.title}</h1><p className="mt-6 max-w-3xl text-xl leading-9 text-muted">{service.description}</p><div className="mt-8 flex flex-wrap gap-3"><LinkButton to="/project-builder" variant="dark">Build with this service</LinkButton><LinkButton to="/contact" variant="secondary">Ask a question</LinkButton></div></div><div className="rounded-[2rem] border border-soft bg-card p-6"><h2 className="font-display text-2xl font-black">Capabilities</h2><ul className="mt-5 space-y-3 text-sm">{service.capabilities.map((item) => <li key={item}>✓ {item}</li>)}</ul></div></div></div></section><section className="section-pad bg-card"><div className="container grid gap-8 lg:grid-cols-3"><div className="lg:col-span-2"><SectionHeader eyebrow="Process" title="How ROVIK delivers this service"/><div className="grid gap-4 md:grid-cols-2">{service.process.map((step, index) => <div key={step} className="rounded-3xl border border-soft p-6"><span className="text-sm font-black text-electric">0{index+1}</span><h3 className="mt-4 font-bold">{step}</h3></div>)}</div></div><div><h3 className="font-display text-2xl font-black">Technologies</h3><div className="mt-4 flex flex-wrap gap-2">{service.technologies.map((tech) => <span key={tech} className="rounded-full border border-soft px-3 py-1 text-sm font-bold">{tech}</span>)}</div></div></div></section><section className="section-pad"><div className="container"><SectionHeader eyebrow="Related work" title="Relevant ROVIK projects"/><div className="grid gap-4 md:grid-cols-3">{related.map((project) => <Link to={`/work/${project.slug}`} className="rounded-[2rem] border border-soft bg-card p-6 transition hover:-translate-y-1" key={project.slug}><p className="kicker">{project.category}</p><h3 className="mt-4 font-display text-2xl font-black">{project.title}</h3><p className="mt-3 text-sm text-muted">{project.summary}</p></Link>)}</div></div></section><section className="section-pad bg-card"><div className="container"><SectionHeader eyebrow="FAQ" title={`${service.title} questions`} /><div className="grid gap-4 md:grid-cols-2">{service.faq.map((faq) => <details key={faq.q} className="rounded-3xl border border-soft p-6"><summary className="cursor-pointer font-bold">{faq.q}</summary><p className="mt-3 text-muted">{faq.a}</p></details>)}</div></div></section></>;
}
